version: '3'

services:
    nodejs-app:
        build: .

        ports:
            - "3000:3000" 

        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
    
        ports:
            - "27017:27017" 